-- DEPRECATED: This file is superseded by the C# DevSeedService.
-- The seed now runs automatically on startup in Development mode.
-- See: api/Common/Seeding/DevSeedService.cs
-- This file is kept for reference only — do NOT run manually.
