namespace Api.Common.Seeding;

internal static partial class PharmacyMasterProductData
{
    internal static readonly SeedProduct[] WomensHealth =
    [
        new("CNST-ED-28", "Levlen ED Tablets", "Women's Health", "Combined oral contraceptive pill", 12.99m, "Levonorgestrel + Ethinylestradiol", "Levlen", "9300608040011", "S4", "28 tablets", "Levonorgestrel 150mcg, Ethinylestradiol 30mcg", "Prescription only. Does not protect against STIs."),
        new("YSMN-28", "Yasmin Tablets", "Women's Health", "Combined oral contraceptive pill", 24.99m, "Drospirenone + Ethinylestradiol", "Yasmin", "9300699000039", "S4", "28 tablets", "Drospirenone 3mg, Ethinylestradiol 30mcg", "Prescription only. May reduce fluid retention."),
        new("NRELS-EC-1", "NorLevo Emergency Contraception", "Women's Health", "Emergency contraceptive (morning after pill)", 19.99m, "Levonorgestrel", "NorLevo", "9300699000040", "S3", "1 tablet", "Levonorgestrel 1.5mg", "Take within 72 hours. Schedule 3 — pharmacist only."),
        new("CLMVX-CRM-35", "Clotrimazole Vaginal Cream 1%", "Women's Health", "Antifungal for vaginal thrush", 9.99m, "Clotrimazole", null, "9300699000041", "Unscheduled", "35g", "Clotrimazole 1%", "Use with applicator as directed."),
        new("PRGNCY-TST-2", "Clearblue Pregnancy Test", "Women's Health", "Digital pregnancy test", 14.99m, null, "Clearblue", "9300699000042", "Unscheduled", "2 tests", null, "Can test from the day of expected period."),
        new("PRGNCY-TST-3", "Clearblue Early Detection Test", "Women's Health", "Early result pregnancy test", 19.99m, null, "Clearblue", "9300699000043", "Unscheduled", "3 tests", null, "Can test up to 6 days before missed period."),
        new("CLMB-CRM-10", "Canesten Combi Thrush Treatment", "Women's Health", "Pessary and cream combination for thrush", 19.99m, "Clotrimazole", "Canesten", "9300699000044", "Unscheduled", "1 pessary + 10g cream", "Clotrimazole 500mg pessary, Clotrimazole 1% cream", null),
        new("MRNA-IMP-1", "Implanon NXT", "Women's Health", "Subdermal contraceptive implant", 39.99m, "Etonogestrel", "Implanon", "9300699000045", "S4", "1 implant", "Etonogestrel 68mg", "Prescription only. Inserted by trained doctor."),
        new("BLKMRS-FLLC-30", "Blackmores Folate 500mcg", "Women's Health", "Folate for pregnancy planning", 9.99m, null, "Blackmores", "9300699000046", "Unscheduled", "90 tablets", "Folic acid 500mcg", "Start 1 month before conception."),
        new("UTCNB-SAC-4", "Ural Sachets Cranberry", "Women's Health", "Urinary alkaliniser for UTI symptoms", 8.99m, "Sodium bicarbonate + Citric acid", "Ural", "9300699000047", "Unscheduled", "28 sachets", "Sodium bicarbonate, Tartaric acid, Citric acid", "For symptomatic relief only. See doctor if symptoms persist."),
        new("PRMPK-CPS-30", "Promensil Menopause Relief", "Women's Health", "Red clover isoflavones for menopause symptoms", 29.99m, null, "Promensil", "9300699000048", "Unscheduled", "30 tablets", "Red clover isoflavones 40mg", null),
        new("OSTRN-GEL-80", "Ovestin Cream 1mg/g", "Women's Health", "Topical oestrogen for vaginal atrophy", 19.99m, "Oestriol", "Ovestin", "9300607250015", "S4", "15g", "Oestriol 1mg/g", "Prescription only."),
        new("NVLRNG-1", "NuvaRing Vaginal Ring", "Women's Health", "Vaginal contraceptive ring", 34.99m, "Etonogestrel + Ethinylestradiol", "NuvaRing", "9300699000049", "S4", "1 ring", "Etonogestrel 11.7mg, Ethinylestradiol 2.7mg", "Prescription only. Insert for 3 weeks, remove for 1 week."),
        new("SPRNLT-50-30", "Spiractin 25mg Tablets", "Women's Health", "Spironolactone for hormonal acne", 14.99m, "Spironolactone", "Spiractin", "9300699000050", "S4", "100 tablets", "Spironolactone 25mg", "Prescription only. Monitor potassium levels."),
        new("BLKMRS-PMT-30", "Blackmores PMT Support", "Women's Health", "PMS symptom relief supplement", 19.99m, null, "Blackmores", "9300699000051", "Unscheduled", "30 tablets", "Vitex agnus-castus 1000mg, Vitamin B6 50mg", null),
        new("SWSSE-MENO-60", "Swisse Menopause Balance", "Women's Health", "Natural menopause symptom support", 29.99m, null, "Swisse", "9300607254022", "Unscheduled", "60 tablets", "Black cohosh 200mg, Sage 1500mg, Calcium 120mg", "Not suitable if you have a history of liver problems."),
        new("BLKMRS-IRON-WMN-30", "Blackmores Pregnancy Iron", "Women's Health", "Gentle iron supplement for pregnancy", 14.99m, null, "Blackmores", "9300607255022", "Unscheduled", "30 tablets", "Iron amino acid chelate 10mg, Vitamin C 100mg", "Gentle on stomach. Suitable during pregnancy."),
        new("PRMPK-FRTE-30", "Promensil Double Strength", "Women's Health", "Double-strength red clover for severe menopause symptoms", 39.99m, null, "Promensil", "9300607256022", "Unscheduled", "30 tablets", "Red clover isoflavones 80mg", null),
        new("DNNSTK-120-28", "Diane-35 ED Tablets", "Women's Health", "Oral contraceptive for acne and contraception", 22.99m, "Cyproterone + Ethinylestradiol", "Diane-35", "9300607257022", "S4", "28 tablets", "Cyproterone acetate 2mg, Ethinylestradiol 35mcg", "Prescription only. Also treats hormonal acne."),
        new("MRNA-IUD-1", "Mirena IUD", "Women's Health", "Hormonal intrauterine device for contraception", 39.99m, "Levonorgestrel", "Mirena", "9300607258022", "S4", "1 device", "Levonorgestrel 52mg", "Prescription only. Inserted by trained doctor. Lasts up to 5 years."),
        new("CRNBRRY-CAP-60", "Swisse Ultiboost High Strength Cranberry", "Women's Health", "Cranberry extract for urinary tract health", 19.99m, null, "Swisse", "9300607259022", "Unscheduled", "60 capsules", "Cranberry extract 25000mg (equivalent)", "Supports urinary tract health."),
        new("BLKMRS-MENO-30", "Blackmores Menopause Day & Night", "Women's Health", "24-hour menopause symptom support", 34.99m, null, "Blackmores", "9300607260022", "Unscheduled", "30 tablets", "Hops extract, Sage, Black cohosh, Valerian", "Day formula for hot flushes, night formula for sleep."),
        new("ELVT-IRNPLS-30", "Elevit Iron Plus", "Women's Health", "Iron supplement specially designed for women", 16.99m, null, "Elevit", "9300607261022", "Unscheduled", "30 tablets", "Iron 24mg, Vitamin C 80mg, Vitamin B12 2mcg", "Gentle on stomach. Take on empty stomach."),
        new("OVLTN-TST-7", "Clearblue Ovulation Test", "Women's Health", "Digital ovulation predictor kit", 39.99m, null, "Clearblue", "9300607262022", "Unscheduled", "10 tests", null, "Identifies 2 most fertile days each cycle."),
        new("NTRFL-EPO-200", "Nature's Own Evening Primrose Oil 1000mg", "Women's Health", "Essential fatty acids for hormonal balance", 16.99m, null, "Nature's Own", "9300607263022", "Unscheduled", "200 capsules", "Evening primrose oil 1000mg (GLA 100mg)", "Traditional support for PMS and skin health."),
        new("UTCNB-URN-28", "Ural Effervescent Powder", "Women's Health", "Urinary alkaliniser for cystitis symptoms", 7.99m, "Sodium bicarbonate + Citric acid", "Ural", "9300607264022", "Unscheduled", "28 sachets", "Sodium citrotartrate, Tartaric acid, Citric acid", "For symptomatic relief only. See doctor if symptoms persist more than 2 days."),
        new("BLKMRS-CALCM-60", "Blackmores Calcium + D3 for Women", "Women's Health", "Calcium with vitamin D for women's bone health", 16.99m, null, "Blackmores", "9300607265022", "Unscheduled", "60 tablets", "Calcium 600mg, Vitamin D3 500IU", "Supports bone density in pre- and post-menopausal women."),
    ];
}
