namespace Api.Common.Seeding;

internal static partial class PharmacyMasterProductData
{
    internal static readonly SeedProduct[] BabyCare =
    [
        new("BPNTN-NAPPY-100", "Bepanthen Nappy Rash Cream", "Baby Care", "Protective nappy rash cream", 9.99m, "Dexpanthenol", "Bepanthen", "9300607500015", "Unscheduled", "100g", "Dexpanthenol 5%", "Apply at each nappy change."),
        new("SDCRM-NAPPY-125", "Sudocrem Antiseptic Healing Cream", "Baby Care", "Multi-purpose baby healing cream", 8.99m, null, "Sudocrem", "9300607321015", "Unscheduled", "125g", "Zinc oxide 15.25%, Benzyl alcohol", "For nappy rash, eczema, minor burns."),
        new("JHNBBY-WSH-500", "Johnson's Baby Top-to-Toe Wash", "Baby Care", "Gentle baby wash for hair and body", 7.99m, null, "Johnson's", "9300607322015", "Unscheduled", "500ml", null, "No more tears formula. pH balanced."),
        new("JHNBBY-LTN-200", "Johnson's Baby Lotion", "Baby Care", "Gentle moisturising baby lotion", 6.99m, null, "Johnson's", "9300607323015", "Unscheduled", "200ml", null, "Hypoallergenic. Clinically mild."),
        new("BNJLA-TTH-15", "Bonjela Teething Gel", "Baby Care", "Soothing gel for teething pain", 8.99m, "Lidocaine", "Bonjela", "9300607324015", "Unscheduled", "15g", "Lidocaine hydrochloride 0.87%", "For babies 5 months and over. Apply to gums with clean finger."),
        new("NRFN-BBY-200", "Nurofen for Children Strawberry", "Baby Care", "Ibuprofen liquid for children 3 months+", 9.99m, "Ibuprofen", "Nurofen", "9300607325015", "Unscheduled", "200ml", "Ibuprofen 100mg/5ml", "From 3 months. Use dosing syringe provided."),
        new("PNDL-BBY-200", "Children's Panadol 1-5 Years", "Baby Care", "Paracetamol liquid for young children", 8.99m, "Paracetamol", "Panadol", "9300607326015", "Unscheduled", "200ml", "Paracetamol 120mg/5ml", "Use dosing device provided. Do not exceed 4 doses per day."),
        new("DMTHCN-DRPS-30", "Infacol Wind Drops", "Baby Care", "Simeticone drops for infant colic and wind", 9.99m, "Simeticone", "Infacol", "9300607327015", "Unscheduled", "50ml", "Simeticone 40mg/ml", "Give before each feed."),
        new("GSTRL-SOL-200", "Gastrolyte Electrolyte Sachets", "Baby Care", "Oral rehydration solution for infants", 9.99m, null, "Gastrolyte", "9300607328015", "Unscheduled", "10 sachets", "Sodium, Potassium, Glucose, Citrate", "Dissolve in 200ml water. For dehydration from illness."),
        new("S26-GOLD-900", "S-26 Gold Infant Formula", "Baby Care", "Stage 1 infant formula 0-6 months", 24.99m, null, "S-26", "9300607329015", "Unscheduled", "900g", null, "From birth. Breastmilk is best for babies."),
        new("APTMIL-GOLD-900", "Aptamil Gold+ Stage 2", "Baby Care", "Follow-on formula 6-12 months", 26.99m, null, "Aptamil", "9300607330015", "Unscheduled", "900g", null, "From 6 months. Follow preparation instructions carefully."),
        new("NUK-BTL-260", "NUK First Choice Bottle", "Baby Care", "Anti-colic baby bottle", 14.99m, null, "NUK", "9300607331015", "Unscheduled", "260ml", null, "BPA free. Temperature control."),
        new("PGRN-WIPES-80", "WaterWipes Baby Wipes", "Baby Care", "Pure water baby wipes", 6.99m, null, "WaterWipes", "9300607332015", "Unscheduled", "80 wipes", "99.9% water, Fruit extract", "Suitable from birth. Biodegradable."),
        new("VTKDS-DRP-20", "Ostelin Vitamin D Kids Liquid", "Baby Care", "Vitamin D drops for infants and children", 14.99m, null, "Ostelin", "9300607333015", "Unscheduled", "20ml", "Cholecalciferol 400IU per 0.5ml", "From birth. Add to milk or food."),
        new("SNSCN-BBY-200", "Cancer Council Kids SPF50+", "Baby Care", "Gentle sunscreen for children", 12.99m, null, "Cancer Council", "9300607334015", "Unscheduled", "200ml", null, "Suitable from 6 months. Reapply every 2 hours."),
        new("FRDNC-SAL-20", "Fess Little Noses Saline Drops", "Baby Care", "Saline drops for blocked baby noses", 7.99m, null, "Fess", "9300607335015", "Unscheduled", "25ml", "Sodium chloride 0.9%", "For newborns and infants."),
        new("PNDL-SUPP-10", "Panadol Children's Suppositories", "Baby Care", "Paracetamol suppositories for children", 8.99m, "Paracetamol", "Panadol", "9300607336015", "Unscheduled", "10 suppositories", "Paracetamol 125mg", "For children 1-5 years who cannot take oral medicine."),
        new("GRPWTR-150", "Infants' Friend Oral Liquid", "Baby Care", "Traditional gripe water for colic relief", 7.99m, null, "Infants' Friend", "9300607337015", "Unscheduled", "150ml", "Dill seed oil, Sodium bicarbonate", "From 1 month. Give before or after feeds."),
        new("SDCRM-NAPPY-400", "Sudocrem Antiseptic Healing Cream Large", "Baby Care", "Value-size multi-purpose baby healing cream", 16.99m, null, "Sudocrem", "9300607338015", "Unscheduled", "400g", "Zinc oxide 15.25%, Benzyl alcohol", "For nappy rash, eczema, minor burns."),
        new("BPNTN-DTMN-30", "Bepanthen First Aid Cream", "Baby Care", "Antiseptic cream for minor cuts and grazes in children", 9.99m, "Dexpanthenol + Chlorhexidine", "Bepanthen", "9300607339015", "Unscheduled", "30g", "Dexpanthenol 5%, Chlorhexidine 0.5%", "Suitable for infants."),
        new("NAN-GOLD-800", "NAN Optipro Gold Stage 1", "Baby Care", "Premium infant formula 0-6 months", 29.99m, null, "NAN", "9300607340015", "Unscheduled", "800g", null, "From birth when breastfeeding is not possible. Follow preparation instructions."),
        new("APTMIL-PROFUT-900", "Aptamil Profutura Stage 1", "Baby Care", "Premium infant formula with HMOs", 34.99m, null, "Aptamil", "9300607341015", "Unscheduled", "900g", null, "From birth. Contains human milk oligosaccharides."),
        new("JHNBBY-OIL-200", "Johnson's Baby Oil", "Baby Care", "Gentle moisturising baby oil for massage", 6.99m, null, "Johnson's", "9300607342015", "Unscheduled", "200ml", "Mineral oil", "Hypoallergenic. Suitable for baby massage."),
        new("PGRN-WIPES-240", "WaterWipes Baby Wipes Value Pack", "Baby Care", "Pure water baby wipes triple pack", 16.99m, null, "WaterWipes", "9300607343015", "Unscheduled", "3 x 80 wipes", "99.9% water, Fruit extract", "Suitable from birth. Biodegradable."),
        new("NRFN-BBY-100", "Nurofen for Children Baby 3 Months+", "Baby Care", "Ibuprofen drops for infants from 3 months", 8.99m, "Ibuprofen", "Nurofen", "9300607344015", "Unscheduled", "50ml", "Ibuprofen 40mg/ml", "Concentrated drops. From 3 months. Use syringe provided."),
        new("NUK-DMMY-2", "NUK Space Soother 0-6 months", "Baby Care", "Orthodontic dummy with extra space for baby's skin", 8.99m, null, "NUK", "9300607345015", "Unscheduled", "2 dummies", null, "BPA free. Sterilise before first use."),
        new("PNDL-BBY-INF-200", "Children's Panadol 1-12 Months Drops", "Baby Care", "Paracetamol drops for infants", 8.99m, "Paracetamol", "Panadol", "9300607346015", "Unscheduled", "20ml", "Paracetamol 100mg/ml", "From 1 month. Use dosing syringe. Do not exceed 4 doses per day."),
        new("DMTHCN-GEL-30", "Infacol Teething Gel", "Baby Care", "Topical gel for teething discomfort", 7.99m, null, "Infacol", "9300607347015", "Unscheduled", "15g", "Choline salicylate 8.714%", "From 4 months. Apply with clean finger."),
        new("S26-GOLD-S2-900", "S-26 Gold Follow-On Formula Stage 2", "Baby Care", "Follow-on formula for 6-12 months", 24.99m, null, "S-26", "9300607348015", "Unscheduled", "900g", null, "From 6 months. Follow preparation instructions carefully."),
        new("BBYRSH-CRM-75", "Curash Nappy Rash Cream", "Baby Care", "Zinc and castor oil nappy rash barrier cream", 6.99m, null, "Curash", "9300607349015", "Unscheduled", "75g", "Zinc oxide 12.5%, Castor oil", "Apply at each nappy change."),
        new("CRSHS-WIPES-80", "Curash Baby Wipes Fragrance Free", "Baby Care", "Gentle fragrance-free baby wipes", 4.99m, null, "Curash", "9300607350022", "Unscheduled", "80 wipes", null, "Fragrance free. Alcohol free."),
        new("DRSTN-ORAL-20", "Dymadon for Babies 1-24 Months", "Baby Care", "Paracetamol oral liquid for infants", 7.99m, "Paracetamol", "Dymadon", "9300607351022", "Unscheduled", "60ml", "Paracetamol 120mg/5ml", "From 1 month. Use dosing device provided."),
        new("JHNBBY-PWD-200", "Johnson's Baby Powder", "Baby Care", "Gentle baby powder for freshness", 5.99m, null, "Johnson's", "9300607352022", "Unscheduled", "200g", "Talc-free cornstarch formula", "For external use only. Keep away from baby's face."),
        new("APTMIL-GOLD-S3-900", "Aptamil Gold+ Stage 3 Toddler", "Baby Care", "Toddler milk drink 1-3 years", 24.99m, null, "Aptamil", "9300607353022", "Unscheduled", "900g", null, "From 12 months. Not a substitute for a balanced diet."),
        new("BPNTN-ECZM-50", "Bepanthen Eczema Cream", "Baby Care", "Steroid-free cream for eczema-prone baby skin", 14.99m, null, "Bepanthen", "9300607354022", "Unscheduled", "50g", "Dexpanthenol 5%", "Steroid free. Suitable from birth."),
    ];
}
