namespace Api.Common.Seeding;

internal static partial class PharmacyMasterProductData
{
    internal static readonly SeedProduct[] DigestiveHealth =
    [
        new("LOSC-20-14", "Losec 20mg Capsules", "Digestive Health", "Relief of heartburn and acid reflux", 18.99m, "Omeprazole", "Losec", "9300607350012", "Unscheduled", "14 capsules", "Omeprazole 20mg", "Do not use for more than 14 days without medical advice."),
        new("IMDM-2-12", "Imodium 2mg Capsules", "Digestive Health", "Relief of acute diarrhoea", 10.99m, "Loperamide", "Imodium", "9300607320015", "Unscheduled", "12 capsules", "Loperamide hydrochloride 2mg", "Do not use for children under 12 without medical advice."),
        new("GVSN-LIQ-300", "Gaviscon Original Liquid", "Digestive Health", "Fast relief of heartburn and indigestion", 12.99m, "Sodium alginate", "Gaviscon", "9300607410013", "Unscheduled", "300ml", "Sodium alginate, Sodium bicarbonate, Calcium carbonate", null),
        new("NXUM-20-14", "Nexium 20mg Tablets", "Digestive Health", "Proton pump inhibitor for acid reflux", 19.99m, "Esomeprazole", "Nexium", "9300607040015", "Unscheduled", "14 tablets", "Esomeprazole 20mg", "Do not use for more than 14 days without medical advice."),
        new("SMTG-LIQ-200", "Somac Heartburn Relief", "Digestive Health", "Pantoprazole for heartburn", 16.99m, "Pantoprazole", "Somac", "9300699000001", "Unscheduled", "14 tablets", "Pantoprazole 20mg", "Not for immediate relief. Takes 1-4 days."),
        new("MYKNT-20-48", "Mylanta 2Go Antacid Chewable", "Digestive Health", "Chewable antacid for indigestion", 9.99m, null, "Mylanta", "9300607042015", "Unscheduled", "48 tablets", "Aluminium hydroxide, Magnesium hydroxide, Simethicone", null),
        new("CLXN-SENR-30", "Coloxyl with Senna 50/8mg", "Digestive Health", "Stool softener with laxative", 8.99m, "Docusate + Sennosides", "Coloxyl", "9300699000003", "Unscheduled", "30 tablets", "Docusate sodium 50mg, Sennosides 8mg", "Do not use daily for more than 1 week."),
        new("MVCLM-LIQ-200", "Movicol Sachets", "Digestive Health", "Osmotic laxative for constipation", 14.99m, "Macrogol 3350", "Movicol", "9300699000004", "Unscheduled", "30 sachets", "Macrogol 3350 13.125g per sachet", "Dissolve in water."),
        new("BSCP-TAB-100", "Bisacodyl 5mg Tablets", "Digestive Health", "Stimulant laxative", 5.99m, "Bisacodyl", null, "9300607045015", "Unscheduled", "100 tablets", "Bisacodyl 5mg", "Swallow whole. Do not crush or chew."),
        new("MMBM-TAB-30", "Metamucil Capsules", "Digestive Health", "Fibre supplement for regularity", 19.99m, "Psyllium husk", "Metamucil", "9300699000005", "Unscheduled", "100 capsules", "Psyllium husk 500mg", "Take with a full glass of water."),
        new("FRMXY-500-20", "Flagyl 400mg Tablets", "Digestive Health", "Antibiotic for GI infections", 18.99m, "Metronidazole", "Flagyl", "9300607047015", "S4", "20 tablets", "Metronidazole 400mg", "Prescription only. Do not drink alcohol."),
        new("GVSN-DBL-24", "Gaviscon Dual Action Tablets", "Digestive Health", "Antacid and alginate combination", 11.99m, "Sodium alginate + Antacid", "Gaviscon", "9300607410020", "Unscheduled", "24 tablets", "Sodium alginate, Aluminium hydroxide, Magnesium carbonate", null),
        new("DRCP-200-20", "De-Gas 125mg Capsules", "Digestive Health", "Relief of bloating and gas", 7.99m, "Simethicone", "De-Gas", "9300607048015", "Unscheduled", "24 capsules", "Simethicone 125mg", null),
        new("RNTN-150-28", "Zantac 150mg Tablets", "Digestive Health", "H2 blocker for acid reduction", 12.99m, "Ranitidine", "Zantac", "9300607049015", "S2", "28 tablets", "Ranitidine 150mg", "Do not use for more than 2 weeks without medical advice."),
        new("MTKLD-CHEW-24", "Quick-Eze Original Chewable", "Digestive Health", "Fast-acting antacid tablets", 4.99m, null, "Quick-Eze", "9300607050015", "Unscheduled", "24 tablets", "Calcium carbonate 500mg", null),
        new("PRBIO-CAP-30", "Inner Health Plus Probiotics", "Digestive Health", "Probiotic for digestive health", 29.99m, null, "Inner Health", "9300607051015", "Unscheduled", "30 capsules", "Lactobacillus acidophilus, Bifidobacterium lactis (25 billion CFU)", "Store in refrigerator."),
        new("ONDST-4-10", "Ondansetron 4mg Tablets", "Digestive Health", "Anti-nausea medication", 15.99m, "Ondansetron", null, "9300607052015", "S4", "10 tablets", "Ondansetron 4mg", "Prescription only."),
        new("MLXCM-LIQ-500", "Mylanta Liquid Antacid", "Digestive Health", "Liquid antacid for heartburn", 11.99m, null, "Mylanta", "9300699000002", "Unscheduled", "500ml", "Aluminium hydroxide, Magnesium hydroxide", null),
        new("PSLN-FIBRE-72", "Metamucil Smooth Orange", "Digestive Health", "Psyllium fibre supplement powder", 24.99m, "Psyllium husk", "Metamucil", "9300607046022", "Unscheduled", "72 doses", "Psyllium husk 3.4g per dose", "Mix with water. Take with a full glass of water."),
        new("GVSN-ADVC-24", "Gaviscon Advance Peppermint Liquid", "Digestive Health", "Long-lasting heartburn and reflux relief", 14.99m, "Sodium alginate", "Gaviscon", "9300607410027", "Unscheduled", "300ml", "Sodium alginate, Potassium bicarbonate", "Take after meals and at bedtime."),
        new("FBRGL-TAB-100", "Fybogel Sachets Orange", "Digestive Health", "Ispaghula husk fibre supplement for regularity", 14.99m, "Ispaghula husk", "Fybogel", "9300607053015", "Unscheduled", "30 sachets", "Ispaghula husk 3.5g per sachet", "Mix with water. Drink immediately."),
        new("CLXN-120-30", "Coloxyl 120mg Tablets", "Digestive Health", "Stool softener for constipation", 7.99m, "Docusate", "Coloxyl", "9300607054015", "Unscheduled", "100 tablets", "Docusate sodium 120mg", "Take with plenty of water."),
        new("IMDM-INST-6", "Imodium Instants", "Digestive Health", "Melt-on-tongue anti-diarrhoeal tablets", 11.99m, "Loperamide", "Imodium", "9300607320022", "Unscheduled", "6 tablets", "Loperamide hydrochloride 2mg", "Place on tongue to dissolve. From 12 years."),
        new("MTKLD-LIQ-200", "Quick-Eze Liquid Heartburn Relief", "Digestive Health", "Liquid antacid for fast heartburn relief", 6.99m, null, "Quick-Eze", "9300607055015", "Unscheduled", "200ml", "Calcium carbonate, Magnesium hydroxide", null),
        new("LOSC-10-28", "Losec Extra 10mg Capsules", "Digestive Health", "Low-dose omeprazole for maintenance", 14.99m, "Omeprazole", "Losec", "9300607350019", "Unscheduled", "28 capsules", "Omeprazole 10mg", "For ongoing heartburn management."),
        new("COLPRM-IBS-20", "Colpermin IBS Relief", "Digestive Health", "Peppermint oil capsules for IBS symptoms", 14.99m, "Peppermint oil", "Colpermin", "9300607056015", "Unscheduled", "20 capsules", "Peppermint oil 0.2ml", "Swallow whole. Do not chew. Take before meals."),
        new("BSCDY-SUPP-12", "Bisacodyl 10mg Suppositories", "Digestive Health", "Stimulant laxative suppositories for quick relief", 6.99m, "Bisacodyl", null, "9300607057015", "Unscheduled", "12 suppositories", "Bisacodyl 10mg", "Insert rectally. Works within 20-60 minutes."),
        new("LACTSE-TAB-60", "Lacteeze Extra Strength Tablets", "Digestive Health", "Lactase enzyme for lactose intolerance", 12.99m, null, "Lacteeze", "9300607058015", "Unscheduled", "60 tablets", "Lactase enzyme 4000 FCC units", "Take before consuming dairy products."),
        new("GSTRLYT-EFVS-10", "Gastrolyte Effervescent Tablets", "Digestive Health", "Oral rehydration for diarrhoea-related dehydration", 9.99m, null, "Gastrolyte", "9300607059015", "Unscheduled", "20 tablets", "Sodium, Potassium, Glucose, Citrate", "Dissolve 1 tablet in 200ml water."),
        new("PRBIO-LQ-200", "Inner Health Plus Dairy Free Probiotic", "Digestive Health", "Dairy-free probiotic for digestive health", 32.99m, null, "Inner Health", "9300699000006", "Unscheduled", "30 capsules", "Lactobacillus rhamnosus, Bifidobacterium animalis (25 billion CFU)", "Dairy free. Store in refrigerator."),
        new("DRCP-CHEW-24", "De-Gas Forte Chewable Tablets", "Digestive Health", "Extra-strength bloating and gas relief", 9.99m, "Simethicone", "De-Gas", "9300607048022", "Unscheduled", "24 tablets", "Simethicone 250mg", "Chew thoroughly before swallowing."),
        new("ANTDS-GEL-200", "Mylanta 2Go Antacid Liquid", "Digestive Health", "Liquid antacid for heartburn and indigestion", 10.99m, null, "Mylanta", "9300607042029", "Unscheduled", "200ml", "Aluminium hydroxide, Magnesium hydroxide, Simethicone", "Shake well before use."),
        new("SNNKT-TAB-30", "Senokot Tablets", "Digestive Health", "Gentle overnight laxative with senna", 8.99m, "Sennosides", "Senokot", "9300699000007", "Unscheduled", "50 tablets", "Sennosides B 7.5mg", "Take at bedtime. Works overnight."),
        new("MTKLD-ULTRA-20", "Quick-Eze Extra Strength Chewable", "Digestive Health", "Extra-strength fast-acting antacid", 5.99m, null, "Quick-Eze", "9300699000008", "Unscheduled", "20 tablets", "Calcium carbonate 680mg, Magnesium hydroxide", null),
        new("IMDM-ADV-12", "Imodium Advanced Chewable", "Digestive Health", "Anti-diarrhoeal with simethicone for gas relief", 13.99m, "Loperamide + Simethicone", "Imodium", "9300607320029", "Unscheduled", "12 tablets", "Loperamide 2mg, Simethicone 125mg", "Chew before swallowing."),
        new("NXUM-40-28", "Nexium HP7 Triple Therapy", "Digestive Health", "Triple therapy for H. pylori eradication", 44.99m, "Esomeprazole + Amoxicillin + Clarithromycin", "Nexium", "9300699000009", "S4", "7-day pack", "Esomeprazole 20mg, Amoxicillin 1g, Clarithromycin 500mg", "Prescription only. Complete the full 7-day course."),
    ];
}
