namespace Api.Common.Seeding;

internal static partial class PharmacyMasterProductData
{
    internal static readonly SeedProduct[] OralCare =
    [
        new("CLGT-TOTAL-110", "Colgate Total Original Toothpaste", "Oral Care", "Multi-benefit fluoride toothpaste", 5.99m, null, "Colgate", "9300607270015", "Unscheduled", "110g", "Sodium fluoride 0.32%, Zinc citrate, Arginine", null),
        new("SNDN-RPRFR-110", "Sensodyne Rapid Relief Toothpaste", "Oral Care", "For sensitive teeth", 9.99m, null, "Sensodyne", "9300607271015", "Unscheduled", "110g", "Stannous fluoride 0.454%", "Use twice daily for ongoing sensitivity relief."),
        new("LSTNE-CMPLT-500", "Listerine Total Care Mouthwash", "Oral Care", "Antibacterial mouthwash", 8.99m, null, "Listerine", "9300607272015", "Unscheduled", "500ml", "Essential oils, Sodium fluoride 0.022%", "Do not swallow. Rinse for 30 seconds."),
        new("ORALB-FLSS-50", "Oral-B Glide Floss", "Oral Care", "Smooth dental floss", 4.99m, null, "Oral-B", "9300607273015", "Unscheduled", "50m", null, "Use daily between teeth."),
        new("PLRDNT-TAB-36", "Polident Denture Cleanser Tablets", "Oral Care", "Effervescent denture cleaning tablets", 7.99m, null, "Polident", "9300607274015", "Unscheduled", "36 tablets", null, "Soak dentures daily for 3-5 minutes."),
        new("FXDNT-CRM-40", "Fixodent Denture Adhesive Cream", "Oral Care", "Denture adhesive for secure fit", 9.99m, null, "Fixodent", "9300607275015", "Unscheduled", "40g", null, "Apply sparingly. Remove dentures and clean daily."),
        new("SNDN-WHTN-110", "Sensodyne True White Toothpaste", "Oral Care", "Whitening toothpaste for sensitive teeth", 10.99m, null, "Sensodyne", "9300607276015", "Unscheduled", "110g", "Sodium fluoride, Potassium nitrate 5%", null),
        new("CLGT-SNSTV-110", "Colgate Sensitive Pro-Relief", "Oral Care", "Pro-argin toothpaste for sensitivity", 8.99m, null, "Colgate", "9300607277015", "Unscheduled", "110g", "Arginine 8%, Calcium carbonate, Sodium fluoride", null),
        new("CRSC-MWSH-500", "Corsodyl Mouthwash", "Oral Care", "Chlorhexidine antiseptic mouthwash", 14.99m, "Chlorhexidine", "Corsodyl", "9300607278015", "Unscheduled", "300ml", "Chlorhexidine digluconate 0.2%", "Use for up to 2 weeks. May stain teeth with prolonged use."),
        new("TPKBRSH-SNIC-1", "Oral-B Smart Electric Toothbrush", "Oral Care", "Rechargeable electric toothbrush", 89.99m, null, "Oral-B", "9300607279015", "Unscheduled", "1 brush + 2 heads", null, "Replace brush head every 3 months."),
        new("SMLNX-GEL-10", "SM-33 Oral Gel", "Oral Care", "Topical anaesthetic for mouth ulcers", 8.99m, "Lidocaine", "SM-33", "9300607280015", "Unscheduled", "10g", "Lidocaine hydrochloride 2%", "Apply to ulcer up to 4 times daily."),
        new("BNJL-MWSH-200", "Bonjela Mouth Ulcer Gel", "Oral Care", "Gel for mouth ulcers and teething", 9.99m, "Choline salicylate", "Bonjela", "9300607281015", "Unscheduled", "15g", "Choline salicylate 8.714%", "Do not use in children under 16 (contains salicylate)."),
        new("DFLR-RNSE-500", "Colgate FluoriGard Rinse", "Oral Care", "Fluoride rinse for cavity prevention", 6.99m, null, "Colgate", "9300607282015", "Unscheduled", "500ml", "Sodium fluoride 0.05%", "Do not swallow. For adults and children over 6."),
        new("ORALB-RPLC-4", "Oral-B Precision Clean Refills", "Oral Care", "Replacement electric toothbrush heads", 24.99m, null, "Oral-B", "9300607283015", "Unscheduled", "4 heads", null, "Replace every 3 months."),
        new("BTXHLD-12", "Biotene Dry Mouth Moisturising Gel", "Oral Care", "Relief for chronic dry mouth", 12.99m, null, "Biotene", "9300607284015", "Unscheduled", "42g", null, "Apply to gums and tongue as needed."),
        new("SNDN-RPRRP-110", "Sensodyne Repair & Protect Toothpaste", "Oral Care", "NovaMin toothpaste for sensitivity repair", 10.99m, null, "Sensodyne", "9300607285015", "Unscheduled", "110g", "Stannous fluoride 0.454%, NovaMin", "Brush twice daily for ongoing repair and protection."),
        new("CLGT-OPTIC-110", "Colgate Optic White Expert Toothpaste", "Oral Care", "Professional whitening toothpaste", 12.99m, null, "Colgate", "9300607286015", "Unscheduled", "110g", "Hydrogen peroxide 1.5%, Sodium fluoride", "Visibly whiter teeth in 1 week."),
        new("LSTNE-ZERO-500", "Listerine Zero Alcohol Mouthwash", "Oral Care", "Alcohol-free antibacterial mouthwash", 8.99m, null, "Listerine", "9300607287015", "Unscheduled", "500ml", "Sodium fluoride 0.022%", "Alcohol free. Less intense taste."),
        new("PLRDNT-OVR-36", "Polident Overnight Denture Cleanser", "Oral Care", "Overnight denture soaking tablets", 8.99m, null, "Polident", "9300607288015", "Unscheduled", "36 tablets", null, "Soak dentures overnight for deep cleaning."),
        new("FXDNT-ULT-40", "Fixodent Ultra Max Hold Cream", "Oral Care", "Maximum hold denture adhesive cream", 11.99m, null, "Fixodent", "9300607289015", "Unscheduled", "40g", null, "All-day hold. Food seal."),
        new("PRXD-WHTE-10", "Crest 3D Whitestrips", "Oral Care", "Professional-level teeth whitening strips", 44.99m, null, "Crest", "9300607290022", "Unscheduled", "10 treatments", "Hydrogen peroxide 10%", "Apply for 30 minutes daily. Results in 7 days."),
        new("TPKBRSH-BIO-4", "Oral-B Eco Bamboo Toothbrush", "Oral Care", "Biodegradable bamboo handle toothbrush", 5.99m, null, "Oral-B", "9300607291022", "Unscheduled", "1 brush", null, "Compostable handle. Soft bristles."),
        new("CRSC-GEL-50", "Corsodyl Dental Gel 1%", "Oral Care", "Chlorhexidine dental gel for gum disease", 12.99m, "Chlorhexidine", "Corsodyl", "9300607292022", "Unscheduled", "50g", "Chlorhexidine digluconate 1%", "Apply to gums with toothbrush. Use short-term only."),
        new("BTXHLD-MWSH-500", "Biotene Dry Mouth Mouthwash", "Oral Care", "Moisturising mouthwash for dry mouth relief", 14.99m, null, "Biotene", "9300607293022", "Unscheduled", "500ml", null, "Alcohol free. Use as needed throughout the day."),
        new("INTRDNTL-BRS-10", "TePe Interdental Brushes Mixed Pack", "Oral Care", "Interdental cleaning brushes assorted sizes", 6.99m, null, "TePe", "9300607294022", "Unscheduled", "8 brushes", null, "Use daily between teeth. Replace weekly."),
        new("CLGT-KIDSTP-80", "Colgate Kids Toothpaste Bubble Fruit", "Oral Care", "Children's fluoride toothpaste with fun flavour", 3.99m, null, "Colgate", "9300607295022", "Unscheduled", "80g", "Sodium fluoride 0.1%", "For children 2-6 years. Use pea-sized amount."),
        new("SNDN-PRTCT-110", "Sensodyne Daily Care Toothpaste", "Oral Care", "Everyday toothpaste for sensitive teeth", 8.99m, null, "Sensodyne", "9300607296022", "Unscheduled", "110g", "Potassium nitrate 5%, Sodium fluoride", "Brush twice daily."),
        new("ORALB-STNBR-4", "Oral-B Satin Floss Tape 25m", "Oral Care", "Comfortable satin dental tape", 4.99m, null, "Oral-B", "9300607297022", "Unscheduled", "25m", null, "Wide tape for gentle, effective cleaning."),
        new("PLRDNT-WHTNG-36", "Polident Whitening Denture Cleanser", "Oral Care", "Whitening denture cleaning tablets", 8.99m, null, "Polident", "9300607298022", "Unscheduled", "36 tablets", null, "Restores denture whiteness in 5 minutes."),
        new("CLGT-KIDSTP-50", "Colgate Smiles Kids Toothpaste 0-3 Years", "Oral Care", "Mild fluoride toothpaste for toddlers", 3.49m, null, "Colgate", "9300607299022", "Unscheduled", "50g", "Sodium fluoride 0.04%", "Use a grain-of-rice amount. Supervise brushing."),
        new("LSTNE-GUMCARE-500", "Listerine Gum Care Mouthwash", "Oral Care", "Mouthwash for gum health and plaque control", 8.99m, null, "Listerine", "9300607300022", "Unscheduled", "500ml", "Zinc chloride, Essential oils", "Clinically proven to reduce gum inflammation."),
        new("SNDN-FRESHMNT-110", "Sensodyne Fresh Mint Toothpaste", "Oral Care", "Everyday sensitivity toothpaste with fresh mint", 8.99m, null, "Sensodyne", "9300607301022", "Unscheduled", "110g", "Potassium nitrate 5%, Sodium fluoride", "Brush twice daily for ongoing sensitivity relief."),
    ];
}
