namespace Api.Common.Seeding;

internal static partial class PharmacyMasterProductData
{
    internal static readonly SeedProduct[] EyeCare =
    [
        new("CLRSG-EYE-5", "Chlorsig Eye Drops 0.5%", "Eye Care", "Antibiotic eye drops for bacterial conjunctivitis", 14.99m, "Chloramphenicol", "Chlorsig", "9300607610017", "S3", "5ml", "Chloramphenicol 5mg/ml", "For external eye use only. Discard 28 days after opening. Schedule 3 — pharmacist only."),
        new("SYSTN-EYE-15", "Systane Ultra Eye Drops", "Eye Care", "Lubricating eye drops for dry eyes", 14.99m, null, "Systane", "9300607080015", "Unscheduled", "15ml", "Polyethylene glycol, Propylene glycol", null),
        new("RFRSH-EYE-15", "Refresh Tears Eye Drops", "Eye Care", "Artificial tears for dry eyes", 9.99m, null, "Refresh", "9300607081015", "Unscheduled", "15ml", "Carboxymethylcellulose sodium 0.5%", null),
        new("PTDY-EYE-10", "Patanol Eye Drops", "Eye Care", "Antihistamine eye drops for allergic conjunctivitis", 24.99m, "Olopatadine", "Patanol", "9300607082015", "S4", "5ml", "Olopatadine hydrochloride 0.1%", "Prescription only. For eyes only."),
        new("VSNE-EYE-15", "Visine Original Eye Drops", "Eye Care", "Redness relief eye drops", 7.99m, "Tetrahydrozoline", "Visine", "9300607083015", "Unscheduled", "15ml", "Tetrahydrozoline hydrochloride 0.05%", "Do not use for more than 4 days."),
        new("HYLFRSH-EYE-10", "Hylo-Fresh Eye Drops", "Eye Care", "Preservative-free lubricating drops", 19.99m, null, "Hylo-Fresh", "9300607084015", "Unscheduled", "10ml", "Sodium hyaluronate 0.1%", "Preservative free. Suitable for contact lens wearers."),
        new("OPTRO-CLS-360", "Opti-Free Express Contact Lens Solution", "Eye Care", "Multi-purpose contact lens solution", 16.99m, null, "Opti-Free", "9300607085015", "Unscheduled", "360ml", "Polyquaternium-1, Myristamidopropyl dimethylamine", null),
        new("RNTLM-EYE-360", "ReNu MultiPlus Solution", "Eye Care", "Contact lens care solution", 14.99m, null, "ReNu", "9300607086015", "Unscheduled", "360ml", "Polyhexamethylene biguanide", null),
        new("THRLRS-EYE-30", "TheraTears Eye Drops", "Eye Care", "Preservative-free single-dose tears", 18.99m, null, "TheraTears", "9300607087015", "Unscheduled", "30 vials", "Sodium carboxymethylcellulose 0.25%", "Single-use vials. Discard after use."),
        new("TMPTC-EYE-5", "Tobramycin Eye Drops", "Eye Care", "Antibiotic eye drops", 19.99m, "Tobramycin", null, "9300607088015", "S4", "5ml", "Tobramycin 3mg/ml", "Prescription only. Discard 28 days after opening."),
        new("STLLRS-EYE-10", "Bion Tears Eye Drops", "Eye Care", "Preservative-free lubricating drops", 16.99m, null, "Bion Tears", "9300607089015", "Unscheduled", "28 vials", "Dextran 70, Hydroxypropyl methylcellulose", "Single-use vials."),
        new("SYSTN-GEL-10", "Systane Gel Drops", "Eye Care", "Lubricating gel drops for severe dry eyes", 16.99m, null, "Systane", "9300607090022", "Unscheduled", "10ml", "Polyethylene glycol 400, Propylene glycol, HP-Guar", "For severe dry eye. May cause temporary blurring."),
        new("OPTIV-EYE-15", "Optive Fusion Eye Drops", "Eye Care", "Dual-action lubricating eye drops", 15.99m, null, "Optive", "9300607091022", "Unscheduled", "10ml", "Carboxymethylcellulose 0.5%, Glycerine 0.9%", "Suitable for contact lens wearers."),
        new("HYLFRSH-FRTE-10", "Hylo-Forte Eye Drops", "Eye Care", "High-concentration preservative-free drops for severe dryness", 24.99m, null, "Hylo-Forte", "9300607092022", "Unscheduled", "10ml", "Sodium hyaluronate 0.2%", "Preservative free. Suitable for contact lenses."),
        new("CLRSG-OINT-4", "Chlorsig Eye Ointment 1%", "Eye Care", "Antibiotic eye ointment for bacterial infection", 14.99m, "Chloramphenicol", "Chlorsig", "9300607610024", "S3", "4g", "Chloramphenicol 10mg/g", "Schedule 3 — pharmacist only. Apply at night. Discard after course."),
        new("AOSPT-CLS-360", "AOSept Plus Contact Lens Solution", "Eye Care", "Hydrogen peroxide contact lens disinfecting solution", 19.99m, null, "AOSept", "9300607093022", "Unscheduled", "360ml", "Hydrogen peroxide 3%", "Must neutralise for 6 hours. Do not rinse lenses with solution."),
        new("BTRFX-EYE-5", "Betoptic S Eye Drops", "Eye Care", "Beta-blocker eye drops for glaucoma", 24.99m, "Betaxolol", "Betoptic", "9300607094022", "S4", "5ml", "Betaxolol 2.5mg/ml", "Prescription only. For intraocular pressure reduction."),
        new("RFRSH-PLUS-15", "Refresh Plus Eye Drops", "Eye Care", "Preservative-free single-use artificial tears", 14.99m, null, "Refresh", "9300607095022", "Unscheduled", "30 vials", "Carboxymethylcellulose sodium 0.5%", "Single-use vials. Discard after use."),
        new("OPTFR-RPLN-300", "Opti-Free Replenish Solution", "Eye Care", "Multi-purpose contact lens disinfecting solution", 18.99m, null, "Opti-Free", "9300607096022", "Unscheduled", "300ml", "Polyquaternium-1, ALDOX", "Rinse, disinfect, and store contact lenses."),
        new("XLTNS-EYE-5", "Xalatan Eye Drops", "Eye Care", "Prostaglandin analogue for glaucoma", 44.99m, "Latanoprost", "Xalatan", "9300607097022", "S4", "2.5ml", "Latanoprost 50mcg/ml", "Prescription only. Apply once daily at night."),
        new("CRMLN-EYE-5", "Cromolux Eye Drops 2%", "Eye Care", "Sodium cromoglycate drops for allergic conjunctivitis", 11.99m, "Sodium cromoglycate", "Cromolux", "9300607098022", "Unscheduled", "10ml", "Sodium cromoglycate 2%", "Use regularly for prevention of allergic symptoms."),
        new("RNTLM-BIO-360", "Biotrue Multi-Purpose Solution", "Eye Care", "Bio-inspired contact lens care solution", 16.99m, null, "Biotrue", "9300607099015", "Unscheduled", "360ml", "Hyaluronan, Polyhexamethylene biguanide", "Cleans, rinses, disinfects, and stores contact lenses."),
        new("EYEWSH-STN-500", "Eyestream Eye Wash Station", "Eye Care", "Emergency eye wash station for workplace", 24.99m, null, null, "9300607100022", "Unscheduled", "500ml", "Sodium chloride 0.9%", "For emergency eye irrigation. Check expiry regularly."),
        new("SYSTN-NGHT-10", "Systane Nighttime Eye Ointment", "Eye Care", "Lubricating eye ointment for overnight relief", 14.99m, null, "Systane", "9300607101022", "Unscheduled", "3.5g", "White petrolatum, Mineral oil", "Apply at bedtime. May blur vision temporarily."),
        new("TMLTD-EYE-5", "Timolol 0.5% Eye Drops", "Eye Care", "Beta-blocker for glaucoma and ocular hypertension", 14.99m, "Timolol", null, "9300607102022", "S4", "5ml", "Timolol maleate 5mg/ml", "Prescription only. Apply one drop twice daily."),
        new("VSNE-ADV-15", "Visine Advanced Redness + Irritation Relief", "Eye Care", "Multi-symptom redness relief eye drops", 9.99m, "Tetrahydrozoline + Polyethylene glycol", "Visine", "9300607103022", "Unscheduled", "15ml", "Tetrahydrozoline 0.05%, Polyethylene glycol 1%", "Do not use for more than 4 days."),
        new("SYSTN-CPL-10", "Systane Complete Lubricant Eye Drops", "Eye Care", "All-in-one dry eye relief drops", 17.99m, null, "Systane", "9300607104022", "Unscheduled", "10ml", "Propylene glycol 0.6%, HP-Guar, Mineral oil", "For all types of dry eye."),
        new("RNTLM-SOFT-360", "ReNu Fresh Multi-Purpose Solution", "Eye Care", "Multi-purpose solution for soft contact lenses", 12.99m, null, "ReNu", "9300607105022", "Unscheduled", "360ml", "Polyhexamethylene biguanide, Borate buffer", "Clean, rinse, disinfect, and store soft lenses."),
    ];
}
