namespace Api.Common.Seeding;

internal static partial class PharmacyMasterProductData
{
    internal static readonly SeedProduct[] FirstAid =
    [
        new("BTRDN-CRM-50", "Betadine Antiseptic Cream", "First Aid", "Broad-spectrum antiseptic for cuts and abrasions", 8.99m, "Povidone-iodine", "Betadine", "9310160820013", "Unscheduled", "50g", "Povidone-iodine 10%", "For external use only. Do not use if allergic to iodine."),
        new("BTRDN-LIQ-100", "Betadine Antiseptic Liquid", "First Aid", "Antiseptic solution for wound cleaning", 9.99m, "Povidone-iodine", "Betadine", "9300607190015", "Unscheduled", "100ml", "Povidone-iodine 10%", "For external use only. Dilute for wound irrigation."),
        new("SVLN-SPR-100", "Savlon Antiseptic Spray", "First Aid", "Antiseptic spray for wounds", 7.99m, null, "Savlon", "9300607191015", "Unscheduled", "100ml", "Chlorhexidine gluconate 0.015%, Cetrimide 0.15%", "For external use only."),
        new("BNDPL-ASSTD-50", "Band-Aid Assorted Strips", "First Aid", "Assorted adhesive bandages", 5.99m, null, "Band-Aid", "9300607192015", "Unscheduled", "50 strips", null, "Change daily or when wet."),
        new("BNDPL-FBRC-20", "Band-Aid Fabric Strips", "First Aid", "Fabric adhesive bandages", 4.99m, null, "Band-Aid", "9300607193015", "Unscheduled", "20 strips", null, null),
        new("BRNCR-GEL-50", "Burnaid Gel", "First Aid", "Hydrogel for burns first aid", 12.99m, null, "Burnaid", "9300607194015", "Unscheduled", "50g", "Melaleuca alternifolia (Tea tree) oil in hydrogel", "Apply liberally to burn area."),
        new("STRSTRP-6", "Steri-Strip Wound Closures", "First Aid", "Adhesive wound closure strips", 6.99m, null, "Steri-Strip", "9300607195015", "Unscheduled", "6 strips", null, "Use for minor lacerations. Not for deep wounds."),
        new("CMPRSS-BND-7.5", "Crepe Bandage 7.5cm", "First Aid", "Elastic compression bandage", 4.99m, null, null, "9300607196015", "Unscheduled", "7.5cm x 4m", null, "Washable and reusable."),
        new("GZSWB-10X10-5", "Gauze Swabs 10x10cm Sterile", "First Aid", "Sterile gauze pads for wound dressing", 3.99m, null, null, "9300607197015", "Unscheduled", "5 swabs", null, "Single use. Sterile."),
        new("TPBND-2.5CM", "Micropore Paper Tape 2.5cm", "First Aid", "Hypoallergenic paper surgical tape", 5.99m, null, "Micropore", "9300607198015", "Unscheduled", "2.5cm x 9.1m", null, "Gentle on skin. Breathable."),
        new("STNGZ-SPR-50", "Stingose Spray", "First Aid", "Relief from insect bites and stings", 7.99m, null, "Stingose", "9300607199015", "Unscheduled", "25ml", "Aluminium sulfate 20%", "Apply to affected area. For external use only."),
        new("SLVDN-CRM-50", "Silvadene Cream 1%", "First Aid", "Silver sulfadiazine for burns", 16.99m, "Silver sulfadiazine", "Silvadene", "9300607200015", "S4", "50g", "Silver sulfadiazine 1%", "Prescription only. For burns."),
        new("FRSTADKT-FAM", "First Aid Kit Family", "First Aid", "Comprehensive family first aid kit", 34.99m, null, null, "9300607201015", "Unscheduled", "1 kit", null, "Contains bandages, gauze, antiseptic, scissors, tweezers."),
        new("THRMO-DGT-1", "Digital Thermometer", "First Aid", "Fast-reading digital thermometer", 12.99m, null, null, "9300607202015", "Unscheduled", "1 unit", null, "Beeps when reading is complete. Memory function."),
        new("ICPCK-INST-1", "Instant Ice Pack", "First Aid", "Single-use cold pack for sprains and strains", 3.99m, null, null, "9300607203015", "Unscheduled", "1 pack", null, "Squeeze to activate. Apply to injury for 20 minutes."),
        new("ANTSP-WIPES-20", "Antiseptic Wipes", "First Aid", "Pre-moistened antiseptic cleaning wipes", 4.99m, null, null, "9300607204015", "Unscheduled", "20 wipes", "Benzalkonium chloride 0.1%", "Single use. For external use only."),
        new("BNDGL-TRGL-1", "Triangular Bandage", "First Aid", "Multi-purpose first aid bandage and sling", 3.99m, null, null, "9300607205015", "Unscheduled", "1 bandage", null, "Can be used as sling, bandage, or padding."),
        new("EYEWSH-15", "Eye Wash Solution", "First Aid", "Sterile eye irrigation solution", 8.99m, null, null, "9300607206015", "Unscheduled", "15ml", "Sodium chloride 0.9%", "Single use. For eye irrigation only."),
        new("BNDPL-WTRPF-20", "Band-Aid Waterproof Strips", "First Aid", "Waterproof adhesive bandages", 5.99m, null, "Band-Aid", "9300607207015", "Unscheduled", "20 strips", null, "Stays on in water. Change daily."),
        new("SVLN-CRM-75", "Savlon Antiseptic Cream", "First Aid", "Antiseptic cream for cuts and grazes", 6.99m, null, "Savlon", "9300607208015", "Unscheduled", "75g", "Chlorhexidine gluconate 0.1%, Cetrimide 0.5%", "For external use only."),
        new("BTRDN-SPR-75", "Betadine First Aid Spray", "First Aid", "Antiseptic spray for minor wounds", 9.99m, "Povidone-iodine", "Betadine", "9300607209015", "Unscheduled", "75ml", "Povidone-iodine 5%", "Spray onto wound. For external use only."),
        new("BRNCR-DRSG-5", "Burnaid Burn Dressing 10x10cm", "First Aid", "Pre-soaked hydrogel dressing for burns", 14.99m, null, "Burnaid", "9300607210022", "Unscheduled", "5 dressings", "Hydrogel with tea tree oil", "Apply directly to burn. Seek medical attention for serious burns."),
        new("STRSTRP-12", "Steri-Strip Wound Closures 6mm x 75mm", "First Aid", "Reinforced adhesive wound closure strips", 8.99m, null, "Steri-Strip", "9300607211022", "Unscheduled", "12 strips", null, "For wound edges that need holding together."),
        new("CMPRSS-BND-10", "Crepe Bandage 10cm", "First Aid", "Wide elastic compression bandage", 5.99m, null, null, "9300607212015", "Unscheduled", "10cm x 4m", null, "Washable and reusable. For sprains and strains."),
        new("GZSWB-7.5-10", "Gauze Swabs 7.5x7.5cm Sterile", "First Aid", "Sterile gauze pads for wound care", 3.99m, null, null, "9300607213015", "Unscheduled", "10 swabs", null, "Single use. Sterile packaging."),
        new("TPBND-5CM", "Micropore Paper Tape 5cm", "First Aid", "Wide hypoallergenic paper surgical tape", 7.99m, null, "Micropore", "9300607214015", "Unscheduled", "5cm x 9.1m", null, "Gentle on skin. Easy to tear."),
        new("ELSTPL-HDY-40", "Elastoplast Extra Tough Waterproof Plasters", "First Aid", "Heavy-duty waterproof plasters", 7.99m, null, "Elastoplast", "9300607215015", "Unscheduled", "40 strips", null, "Extra strong adhesion. Waterproof."),
        new("FRSTADKT-TRV", "First Aid Kit Travel", "First Aid", "Compact travel first aid kit", 19.99m, null, null, "9300607216015", "Unscheduled", "1 kit", null, "Contains essentials for travel: plasters, wipes, tape, bandage."),
        new("THRMO-EAR-1", "Braun ThermoScan Ear Thermometer", "First Aid", "Infrared ear thermometer for fast readings", 49.99m, null, "Braun", "9300607217015", "Unscheduled", "1 unit", null, "Pre-warmed tip for accuracy. Memory function."),
        new("ICPCK-REUSE-1", "Reusable Hot Cold Pack", "First Aid", "Gel pack for hot or cold therapy", 9.99m, null, null, "9300607218015", "Unscheduled", "1 pack", null, "Freeze for cold therapy. Microwave for heat therapy."),
        new("BNDPL-KNCKL-10", "Band-Aid Knuckle & Fingertip Plasters", "First Aid", "Shaped plasters for fingers and knuckles", 5.99m, null, "Band-Aid", "9300607219015", "Unscheduled", "10 strips", null, "Flexible fit for awkward areas."),
        new("TWZRS-SS-1", "Stainless Steel Tweezers", "First Aid", "Precision splinter removal tweezers", 7.99m, null, null, "9300607220015", "Unscheduled", "1 pair", null, "Fine-point tips for splinter and tick removal."),
        new("WNDCL-BTL-500", "Normal Saline Wound Irrigation", "First Aid", "Sterile saline for wound cleaning", 6.99m, null, null, "9300607221015", "Unscheduled", "500ml", "Sodium chloride 0.9%", "Sterile. For wound irrigation."),
        new("SCSRS-FH-1", "First Aid Scissors", "First Aid", "Blunt-end scissors for dressings and tape", 5.99m, null, null, "9300607222015", "Unscheduled", "1 pair", null, "Blunt tips for safety. Stainless steel."),
        new("DRSNG-RLR-1", "Conforming Bandage Roll 7.5cm", "First Aid", "Stretch conforming bandage for wound dressing retention", 2.99m, null, null, "9300607223015", "Unscheduled", "7.5cm x 4m", null, "Conforms to body contours. Single use."),
        new("ANTSP-LQUID-100", "Dettol Antiseptic Liquid", "First Aid", "Concentrated antiseptic for wound cleaning", 7.99m, null, "Dettol", "9300607224015", "Unscheduled", "125ml", "Chloroxylenol 4.8%", "Dilute before use. For external use only."),
        new("ELSTPL-BLSTR-5", "Elastoplast Blister Plasters", "First Aid", "Hydrocolloid plasters for blisters", 8.99m, null, "Elastoplast", "9300607225015", "Unscheduled", "5 plasters", null, "Cushions and protects blisters. Waterproof."),
        new("TRNQT-1", "Emergency Tourniquet CAT", "First Aid", "Combat application tourniquet for severe bleeding", 39.99m, null, null, "9300607226015", "Unscheduled", "1 unit", null, "For life-threatening limb haemorrhage. Single use."),
        new("BRNCR-GEL-25", "Burnaid Gel Travel Size", "First Aid", "Compact hydrogel for burns first aid on the go", 6.99m, null, "Burnaid", "9300607227015", "Unscheduled", "25g", "Melaleuca alternifolia (Tea tree) oil in hydrogel", "Portable burn treatment."),
        new("BNDPL-SNG-100", "Band-Aid Standard Strips", "First Aid", "Standard adhesive strips family pack", 7.99m, null, "Band-Aid", "9300607228015", "Unscheduled", "100 strips", null, "Comfortable cushion protection. Change daily."),
    ];
}
